keycloak:
  token-uri: /protocol/openid-connect/token

rest-client:
  keycloak:
    base-url: ${keycloak.host}/realms/${keycloak.realm}
    read-timeout: 1_000

logging:
  level:
    root: warn
    com.lukinhasssss: info

server:
  port: 8082
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.
  undertow:
    threads:
      worker: 64 # Number of worker threads. The default is 8 times the number of I/O threads. Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # Number of I/O threads to create for the worker. The default is derived from the number of available processors.

spring:
  threads.virtual.enabled: true # Habilita o uso de threads virtuais. https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.virtual-threads
  main.keep-alive: true # https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.virtual-threads
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}

management:
  info:
    build:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    enable:
      jvm: true
    distribution:
      slo:
        http: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: assinatura-de-videos
  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: Assinaturas
    description: Microsserviço de assinaturas
    version: 1.0
    java:
      version: 21